### PR TITLE
Resolve parameterized types in the generic handler. (Fixes #163)

### LINKED ISSUE #163: Generic Entry Point fails on base class derived parameterized types in target handler
The Generic Entry Point handler cannot convert to method parameter derived from parameterized types in a base class `RequestHandler`. This happens because the handler looks at the method and then tries to determine the type of argument that was expected and sees a parameterized type. Parameterized types are only set by classes extending implementing the class with the `requestHandler` (which is in the base class).

The following pseudo-code situation will cause this bug:

```java
class Base<I extends StringGetter<I>>
    implements RequestHandler<I, String>
{
    public String handleRequest(I __i, Context __c)
    {
        return __i.getSomeString();
    }
}

interface StringGetter<T>
{
    public abstract String getSomeString(t __t);
}

class POJO
    implements StringGetter<POJO>
{
    public String getSomeString(POJO __t)
    {
         return "Hello!";
    }
}

public class Derived
    extends Base<POJO>
{
}
```

### PR DESCRIPTION
**Pull request by XerTheSquirrel**
This will resolve parameterized types in methods accordingly if they exist.

It also includes some cleanup to make things easier to understand.

### CODE REVIEW

**Comment by XerTheSquirrel** [comment]
This is ready for review!

Note that only the outermost type variable is resolved since this should cover most of the use cases based on how the default classes are written.

File: src/main/java/com/iopipe/generic/EntryPoint.java [hunk 1]
```diff
@@ -577,5 +505,271 @@ else if (pn == 0)
...
+			// anyway)
+			if (pivotdx < 0)
+				return __t;
+			
+			// Peek the current class
+			Class<?> upperclass = stackcopy.peek();
+			
+			// Initializing a class which is just a type variable
+			if (upperclass == null)
+				return __t;
```
Comment (XerTheSquirrel) [inline src/main/java/com/iopipe/generic/EntryPoint.java]: This needs to be changed to `return ObjectTranslator.__unbound(tv)` so at least the base class matches even though we do not really know what it is. Example from #163 `I` will be translated to `StringGetter<I>`.

Comment (XerTheSquirrel) [reply src/main/java/com/iopipe/generic/EntryPoint.java]: Test object `ParameterA<A, B>` should have its bounds changed to  `A extends SomeClass ` that does something.

File: src/main/java/com/iopipe/generic/EntryPoint.java [hunk 2]
```diff
@@ -577,5 +505,271 @@ else if (pn == 0)
...
+					return __Target__.__resolve(stackcopy, ptparms[j]);
+				}
+				
+				// There is something wrong with the parameter, ignore
+				catch (TypeNotPresentException|MalformedParameterizedTypeException e)
+				{
+				}
+				
+				// We found our class so we do not need to look elsewhere
+				// however something was wrong and we could not determine
```
Comment (XerTheSquirrel) [inline src/main/java/com/iopipe/generic/EntryPoint.java]: Reword to say that "We found our class, and we found no type that could be used. All other checks will fail so we just stop.".

**Comment by XerTheSquirrel** [comment]
Okay! So I adjusted a test for the commented case and all is well. So I do not see a need to modify that one line based on the comment.

**Comment by XerTheSquirrel** [comment]
Please re-review for the changes made.
